name: flutter_yappy_checkout
description: Best and easy way to INTEGRATE Yappy checkout in Flutter applications.
version: 1.0.0
homepage: https://github.com/globallistwork-prog/flutter_yappy_checkout

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Si tienes assets o fuentes personalizadas, puedes agregarlas aquí
  # assets:
  #   - assets/logo.png
